-- MySQL Script generated by MySQL Workbench
-- Mon Jul 21 11:25:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema optical_shop_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `optical_shop_db` ;

-- -----------------------------------------------------
-- Schema optical_shop_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optical_shop_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `optical_shop_db`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optical_shop_db`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `optical_shop_db`.`Supplier` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `number` VARCHAR(10) NULL DEFAULT NULL,
  `floor` VARCHAR(10) NULL DEFAULT NULL,
  `door` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `fax` VARCHAR(20) NULL DEFAULT NULL,
  `nif` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `nif` (`nif` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `id_supplier` INT NULL,
  PRIMARY KEY (`id_brand`),
  INDEX `fk_brand_supplier_idx` (`id_supplier` ASC) VISIBLE,
  CONSTRAINT `fk_brand_supplier`
    FOREIGN KEY (`id_supplier`)
    REFERENCES `optical_shop_db`.`Supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Glasses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `id_glasses` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `left_lens_prescription` DECIMAL(4,2) NOT NULL,
  `right_lens_prescription` DECIMAL(4,2) NOT NULL,
  `frame_type` ENUM('full-rim', 'half-rim', 'rimless') NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `left_lens_color` VARCHAR(45) NOT NULL,
  `right_lens_color` VARCHAR(45) NOT NULL,
  `id_brand` INT NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `fk_glasses_brand_idx` (`id_brand` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `mydb`.`Brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `optical_shop_db` ;

-- -----------------------------------------------------
-- Table `optical_shop_db`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optical_shop_db`.`Client` ;

CREATE TABLE IF NOT EXISTS `optical_shop_db`.`Client` (
  `id_client` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `number` VARCHAR(10) NULL DEFAULT NULL,
  `floor` VARCHAR(10) NULL DEFAULT NULL,
  `door` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `registration_date` DATE NOT NULL,
  `referred_by_id_client` INT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `fk_client_referred_by_idx` (`referred_by_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_referred_by`
    FOREIGN KEY (`referred_by_id_client`)
    REFERENCES `optical_shop_db`.`Client` (`id_client`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optical_shop_db`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optical_shop_db`.`Employee` ;

CREATE TABLE IF NOT EXISTS `optical_shop_db`.`Employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `nif` VARCHAR(20) NOT NULL,
  `role` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `nif` (`nif` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optical_shop_db`.`Sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optical_shop_db`.`Sale` ;

CREATE TABLE IF NOT EXISTS `optical_shop_db`.`Sale` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `sale_date` DATETIME NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `id_client` INT NOT NULL,
  `id_employee` INT NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `fk_sale_client` (`id_client` ASC) VISIBLE,
  INDEX `fk_sale_employee` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `fk_sale_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `optical_shop_db`.`Client` (`id_client`),
  CONSTRAINT `fk_sale_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `optical_shop_db`.`Employee` (`id_employee`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optical_shop_db`.`Sale_Detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optical_shop_db`.`Sale_Detail` ;

CREATE TABLE IF NOT EXISTS `optical_shop_db`.`Sale_Detail` (
  `id_sale_detail` INT NOT NULL AUTO_INCREMENT,
  `id_sale` INT NOT NULL,
  `id_glasses` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_sale_detail`),
  INDEX `fk_sale_detail_glasses_idx` (`id_glasses` ASC) VISIBLE,
  INDEX `fk_Sale_Detail_Sale_idx` (`id_sale` ASC) VISIBLE,
  CONSTRAINT `fk_sale_detail_glasses`
    FOREIGN KEY (`id_glasses`)
    REFERENCES `mydb`.`Glasses` (`id_glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Detail_Sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `optical_shop_db`.`Sale` (`id_sale`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
