-- MySQL Script generated by MySQL Workbench
-- Sun Jul 13 01:03:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`provinces` ;

CREATE TABLE IF NOT EXISTS `mydb`.`provinces` (
  `id_province` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id_locations` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_province` INT NOT NULL,
  PRIMARY KEY (`id_locations`),
  INDEX `fk_locations_province_idx` (`id_province` ASC) VISIBLE,
  CONSTRAINT `fk_locations_province`
    FOREIGN KEY (`id_province`)
    REFERENCES `mydb`.`provinces` (`id_province`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id_customers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `address` VARCHAR(100) NULL,
  `postal_code` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `id_location` INT NOT NULL,
  PRIMARY KEY (`id_customers`),
  INDEX `fk_customers_location_idx` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_customers_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `mydb`.`locations` (`id_locations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stores` (
  `id_stores` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `id_location` INT NOT NULL,
  PRIMARY KEY (`id_stores`),
  INDEX `fk_stores_location_idx` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_stores_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `mydb`.`locations` (`id_locations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`employees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id_employees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `employee_type` ENUM('cook', 'delivery_driver', 'manager') NOT NULL,
  `id_store` INT NOT NULL,
  PRIMARY KEY (`id_employees`),
  INDEX `fk_employees_store_idx` (`id_store` ASC) VISIBLE,
  CONSTRAINT `fk_employees_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `mydb`.`stores` (`id_stores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id_orders` INT NOT NULL AUTO_INCREMENT,
  `order_datetime` DATETIME NOT NULL,
  `order_type` ENUM('delivery', 'pickup') NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `id_customer` INT NOT NULL,
  `id_store` INT NOT NULL,
  `id_delivery_employee` INT NULL,
  `delivery_datetime` DATETIME NULL,
  PRIMARY KEY (`id_orders`),
  INDEX `fk_orders_customer_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_orders_store_idx` (`id_store` ASC) VISIBLE,
  INDEX `id_delivery_employee_idx` (`id_delivery_employee` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`customers` (`id_customers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `mydb`.`stores` (`id_stores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_delivery_employee`
    FOREIGN KEY (`id_delivery_employee`)
    REFERENCES `mydb`.`employees` (`id_employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_categories` (
  `id_pizza_categories` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_pizza_categories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT(100) NULL,
  `image_url` VARCHAR(300) NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `product_type` ENUM('pizza', 'hamburger', 'drink') NOT NULL,
  `id_pizza_category` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_products_pizza_category_idx` (`id_pizza_category` ASC) VISIBLE,
  CONSTRAINT `fk_products_pizza_category`
    FOREIGN KEY (`id_pizza_category`)
    REFERENCES `mydb`.`pizza_categories` (`id_pizza_categories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_items` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  `intem_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_order`, `id_product`),
  INDEX `fk_order_items_product_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `mydb`.`orders` (`id_orders`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_items_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`products` (`id_product`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
