-- MySQL Script generated by MySQL Workbench
-- Sun Jul 13 17:28:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NULL,
  `date_of_birth` DATETIME NULL,
  `gender` ENUM('male', 'female', 'other', 'prefer not to say') NULL,
  `country` VARCHAR(100) NULL,
  `zip_code` VARCHAR(10) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `size_mb` DECIMAL(10,2) NULL,
  `file_name` VARCHAR(45) NULL,
  `duration_seconds` INT NULL,
  `thumbnail_url` VARCHAR(500) NULL,
  `views_count` INT NULL,
  `likes_count` INT NULL,
  `dislikes_count` INT NULL,
  `status` ENUM('public', 'hidden', 'private') NOT NULL,
  `publication_date` DATETIME NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_video`),
  INDEX `fk_video_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_video_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tag`),
  UNIQUE INDEX `tag_name_UNIQUE` (`tag_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`channel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`channel` (
  `id_channel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `decription` MEDIUMTEXT NULL,
  `creation_date` DATETIME NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_channel`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_channel_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `creation_date` DATETIME NULL,
  `status` ENUM('public', 'private') NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `fk_playlist_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NULL,
  `date_time` DATETIME NULL,
  `id_user` INT NULL,
  `id_video` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_comment_id_video_idx` (`id_video` ASC) VISIBLE,
  CONSTRAINT `fk_comment_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_id_video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mydb`.`video` (`id_video`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video_tag` (
  `id_video` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`id_video`, `id_tag`),
  INDEX `fk_VideoTag_Tag_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `fk_VideoTag_Video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mydb`.`video` (`id_video`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VideoTag_Tag`
    FOREIGN KEY (`id_tag`)
    REFERENCES `mydb`.`tag` (`id_tag`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subscription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `id_user` INT NOT NULL,
  `id-channel` INT NOT NULL,
  `subscription_date` DATETIME NULL,
  PRIMARY KEY (`id_user`, `id-channel`),
  INDEX `fk_Subscription_Channel_idx` (`id-channel` ASC) VISIBLE,
  CONSTRAINT `fk_Subscription_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Subscription_Channel`
    FOREIGN KEY (`id-channel`)
    REFERENCES `mydb`.`channel` (`id_channel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`video_reaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`video_reaction` (
  `id_user` INT NOT NULL,
  `id_video` INT NOT NULL,
  `reaction_type` ENUM('like', 'dislike') NULL,
  `reaction_date_time` DATETIME NULL,
  PRIMARY KEY (`id_user`, `id_video`),
  INDEX `fk_VideoReaction_Video_idx` (`id_video` ASC) VISIBLE,
  CONSTRAINT `fk_VideoReaction_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VideoReaction_Video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mydb`.`video` (`id_video`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlist_video` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlist_video` (
  `id_playlist` INT NOT NULL,
  `id_video` INT NOT NULL,
  `video_order` INT NULL,
  PRIMARY KEY (`id_playlist`, `id_video`),
  INDEX `fk_PlaylistVideo_Video_idx` (`id_video` ASC) VISIBLE,
  CONSTRAINT `fk_PlaylistVideo_Playlist`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `mydb`.`playlist` (`id_playlist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PlaylistVideo_Video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mydb`.`video` (`id_video`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment_reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment_reaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment_reaction` (
  `id_user` INT NOT NULL,
  `id_comment` INT NOT NULL,
  `reaction_type` ENUM('like', 'dislike') NULL,
  `reaction_date_time` DATETIME NULL,
  PRIMARY KEY (`id_user`, `id_comment`),
  INDEX `fk_CommentReaction_Comment_idx` (`id_comment` ASC) VISIBLE,
  CONSTRAINT `fk_CommentReaction_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CommentReaction_Comment`
    FOREIGN KEY (`id_comment`)
    REFERENCES `mydb`.`comment` (`id_comment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
